-- Remove the conflict between FEATURE_LAKE == FEATURE_ICE and FEATURE_RIVER == FEATURE_JUNGLE
UPDATE FakeFeatures SET ID=ID+200;

ALTER TABLE Buildings
  ADD AddsFreshWater INTEGER DEFAULT 0;
ALTER TABLE Buildings
  ADD PurchaseOnly INTEGER DEFAULT 0;
ALTER TABLE Building_ThemingBonuses
  ADD ConsecutiveEras INTEGER DEFAULT 0;

ALTER TABLE Improvements
  ADD AddsFreshWater INTEGER DEFAULT 0;






ALTER TABLE Projects ADD COLUMN 'Maintenance' INTEGER DEFAULT 0;
ALTER TABLE Projects ADD COLUMN 'CostScalerEra' INTEGER DEFAULT 0;
ALTER TABLE Projects ADD COLUMN 'CostScalerNumRepeats' INTEGER DEFAULT 0;
ALTER TABLE Projects ADD COLUMN 'CityMaxNum' INTEGER DEFAULT 0;

ALTER TABLE Buildings ADD 'HumanOnly' INTEGER DEFAULT 0;


INSERT INTO CustomModDbUpdates(Name, Value) VALUES('API_EXTENSIONS', 1);
